site_name: Carol Shaw
repo_url: https://github.com/
repo_name: G04_Carol-Shaw

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Atas:
    - Ata 01: Atas/ata.md
  - Planejamento:
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologias.md
    - Políticas: Planejamento/Políticas.md
    - SQuaRe: Planejamento/SQuaRe.md
    - Projeto: Planejamento/Projeto.md
  - Definição:
    - Usabilidade: Definicao/usabilidade.md
    - Confiabilidade: Definicao/confiabilidade.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  language: pt-BR
  logo: assets/icon.png
  favicon: assets/icon.png

